# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]   # Define operating systems
        arch: [amd64]                 # Define architectures

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      
      # Build for the target platform
      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          output="dist/myprogram-${{ matrix.os }}-${{ matrix.arch }}"
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $output

      # Upload the build output as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/myprogram-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: myprogram-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream